
development:
  adapter: postgresql
  encoding: unicode
  database: thoughtsy_development
  pool: 5
  username: adam
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: thoughtsy_test
  pool: 5
  username: adam
  password: password1
